### ISSUE TITLE
Composite function output

### ISSUE THREAD

**Issue by faber6911** [schmiph2/pysepm#3]
Hi, great package.
I just have one question, I guess the composite function outputs SIG, BAK and OVL measurements, but in what order?
![image](https://user-images.githubusercontent.com/45421256/91886267-5f31df00-ec89-11ea-8ae5-f0cb18df12f6.png)

**Comment by schmiph2** [comment]
Hi, thank you! They are in the following order: (SIG, BAK, OVL).

**Comment by faber6911** [comment]
Hi, thank you very much for confirming!
